### ISSUE TITLE
APK of last version missing

### ISSUE THREAD

**Issue by IzzySoft** [75py/Aplin#125]
Could you please add the APK of the latest version to the releases page? Thanks!

**Comment by IzzySoft** [comment]
@75py any chance? Or did you abandon this project? 😱

**Comment by 75py** [comment]
@IzzySoft I added the apk file on this page.
https://github.com/75py/Aplin/releases/tag/3.3.1

I don't abandon it.
But in the future Android versions, reflection may become unusable. If eflection will become unusable in the future Android versions, maybe I'll abandon it.
https://developer.android.com/about/versions/pie/restrictions-non-sdk-interfaces?hl=en

**Comment by IzzySoft** [comment]
Thanks a lot, @75py! And yes, if you can't make it work anymore, no sense wasting time on a corpse. Until then, all the best for keeping it up!

**Comment by IzzySoft** [comment]
Hi @75py, I just wonder where you put all the APKs now? I see you're still updating the code and tagging releases, but none of the latter has any APK attached for ages. The last one I found was a 3.3.1 from 3 years ago – and meanwhile the tags show you reached 5.1.0. Any chance you will make the APKs available again (maybe starting with 5.1.0 and attaching the APK to the tag)?

**Comment by 75py** [comment]
Hi @IzzySoft !
I can upload APKs. But why do you need APKs? (This does not mean I don't want to do it, just a question.)
Aplin can be downloaded from Google Play.

**Comment by IzzySoft** [comment]
There are many folks not using Play – either because they cannot (running devices without the Google stack), want not (for privacy reasons), or both (like me: running without the Google stack for privacy reasons :smile:). We instead use e.g. F-Droid. There are many F-Droid repositories out there; while F-Droid itself compiles all apps from source, it has strict inclusion rules (like no proprietary components being allowed). Each repo can make its own rules; mine e.g. has slightly relaxed ones (permitting "minor violations") – but I cannot compile from source, so I need the APK. To provide it to those using [my repo](https://apt.izzysoft.de/fdroid/repo), which somehow got a rather large user base meanwhile…

**Comment by 75py** [comment]
@IzzySoft Sorry for the late reply.
I see, I understand.
I'll attach the APK file from the next release!
https://github.com/75py/Aplin/releases/tag/5.4.0

**Comment by 75py** [comment]
@IzzySoft Thank you very much!

> So do you want my updater to pick up pre-releases as well in the future, or just the stable ones?

Please use the stable version. (Pre-release is the equivalent of an open beta on Google Play. )

**Comment by IzzySoft** [comment]
OK, thanks – then all remains as-is and no change necessary at my end.
